/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef, useEffect } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { degToRad } from "three/src/math/MathUtils.js";
import { useAtomValue } from "jotai";
import { mapaTextureSrcAtom } from "./UI";

/** Ventana centrada [-1,1]: X → rotation.z, Y → rotation.x, cada una ±5°. */
const MAP_CURSOR_TILT_DEG = 5;

const Mapa = (props) => {
  const { nodes } = useGLTF("/models/Mapa_Model.glb");
  const meshRef = useRef(null);
  const cursorRef = useRef({ x: 0, y: 0 });

  // const mapaTexture = useTexture("./textures/MP/Mapa.jpg");
  // mapaTexture.flipY = true;
  // mapaTexture.colorSpace = THREE.SRGBColorSpace;
  const textureSrc = useAtomValue(mapaTextureSrcAtom);
  const mapaTexture = useTexture(textureSrc);
  mapaTexture.flipY = true;
  mapaTexture.colorSpace = THREE.SRGBColorSpace;

  useEffect(() => {
    mapaTexture.flipY = true;
    mapaTexture.colorSpace = THREE.SRGBColorSpace;
  }, [mapaTexture]);

  const mapaMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      map: mapaTexture,
      toneMapped: false, // prevent threejs from washing colors
    });
  }, [mapaTexture]);

  /** Geometría centrada en el origen para que rotation gire alrededor del centro del mesh. */
  const centeredGeometry = useMemo(() => {
    const g = nodes.mesh_0.geometry.clone();
    g.center();
    return g;
  }, [nodes]);

  useEffect(() => {
    return () => centeredGeometry.dispose();
  }, [centeredGeometry]);

  useEffect(() => {
    const onPointerMove = (e) => {
      const w = window.innerWidth || 1;
      const h = window.innerHeight || 1;
      const halfW = w * 0.5;
      const halfH = h * 0.5;
      cursorRef.current = {
        x: halfW > 0 ? (e.clientX - halfW) / halfW : 0,
        y: halfH > 0 ? (halfH - e.clientY) / halfH : 0,
      };
    };
    window.addEventListener("pointermove", onPointerMove, { passive: true });
    return () => window.removeEventListener("pointermove", onPointerMove);
  }, []);

  useFrame(() => {
    const mesh = meshRef.current;
    if (!mesh) return;
    const { x: cx, y: cy } = cursorRef.current;
    const d = degToRad(MAP_CURSOR_TILT_DEG);
    mesh.rotation.x = -cy * d;
    mesh.rotation.y = 0;
    mesh.rotation.z = -cx * d;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={meshRef}
        castShadow
        receiveShadow
        // geometry={nodes.mesh_0.geometry}
        // material={nodes.mesh_0.material}
        geometry={centeredGeometry}
        material={mapaMaterial}
      />
    </group>
  );
};

useGLTF.preload("/models/Mapa_Model.glb");

export default Mapa;
